### ISSUE TITLE
Does blogging work?

### ISSUE THREAD

**Issue by alex-phillips** [nicksergeant/snipt#176]
Does the blogging work with this if I'm self hosting?

**Comment by nicksergeant** [comment]
@alex-phillips it might work - but it has been years since I've worked on the codebase. IIRC, you'll need to setup wildcard DNS for your installation, as by default the usernames are looked up like `<blog-username>.snipt.net`. Here's all of the logic for the blog username/domain handling:

https://github.com/nicksergeant/snipt/blob/master/blogs/middleware.py

**Comment by alex-phillips** [comment]
@nicksergeant thanks for the response! I'll take a look. I've been using this for quite a while now, just started getting curious and poking around. Thanks for the great work.

**Comment by nicksergeant** [comment]
@alex-phillips awesome! Glad to hear someone still finds a use for it :)
